[package]
name = "serial_manager"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Background serial port discovery and management service"
license = "MIT OR Apache-2.0"

[dependencies]
serialport = "4.0"

[dev-dependencies]
# For examples and tests
tokio = { version = "1.0", features = ["full"] }